# Generated by Django 4.2.6 on 2023-12-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
